export const CURRENCY = 'Rs.'

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const GET_TOPPINGS_REQUEST = 'GET_TOPPINGS_REQUEST'
export const GET_TOPPINGS_SUCCESS = 'GET_TOPPINGS_SUCCESS'
export const GET_TOPPINGS_FAILURE = 'GET_TOPPINGS_FAILURE'

export const MAX_DESCRIPTION_CHARS = 100
